/**
 * Core domain types and the retrieval trace model.
 *
 * RetrievalInspector is built around one idea: every RAG query should be
 * able to explain what it retrieved, why, what context reached the model,
 * and where the final answer came from. These types carry that trace.
 */

/** A single source document added to the pipeline. */
export interface Document {
  /** Stable identifier, e.g. the file path or a DB id. */
  id: string;
  /** Display name, typically the filename. */
  title: string;
  /** One of the supported source formats. */
  format: "pdf" | "markdown" | "txt" | "html";
  /** Raw content before chunking. */
  content: string;
  /** Arbitrary source metadata (author, source URL, tags, ...). */
  metadata?: Record<string, unknown>;
}

/** A chunk: a slice of a document ready for embedding + indexing. */
export interface Chunk {
  id: string;
  documentId: string;
  /** Chunk order within its document (0-based). */
  index: number;
  text: string;
  /**
   * Where this chunk came from inside the source, when the loader could
   * determine it (page number for PDFs, section heading for markdown, ...).
   */
  location?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

/** A scored retrieval hit. */
export interface ScoredResult {
  chunk: Chunk;
  /** Similarity/distance depending on strategy; higher is more relevant. */
  score: number;
  rank: number;
  /** Which strategy produced this hit. */
  strategy: RetrievalStrategy;
}

export type RetrievalStrategy =
  | "vector"
  | "keyword"
  | "hybrid"
  | "reranked";

/** A source citation linking part of the generated answer back to a chunk. */
export interface SourceCitation {
  documentId: string;
  documentTitle: string;
  chunkId: string;
  location?: Record<string, unknown>;
  score?: number;
}

/**
 * The full inspection record for one query. This is the heart of
 * RetrievalInspector — expose it to whoever is debugging the pipeline.
 */
export interface RetrievalTrace {
  query: string;
  /** Raw results per strategy used (vector, keyword, hybrid, reranked). */
  resultsByStrategy: Record<RetrievalStrategy, ScoredResult[]>;
  /** The final merged, ranked result set. */
  finalResults: ScoredResult[];
  /** The exact context string assembled and passed to the LLM. */
  context: string;
  /** Duplicate-content warnings that were pruned while assembling context. */
  prunedDuplicates: ScoredResult[];
  /** Sources connected to the generated answer. */
  sources: SourceCitation[];
  /** When the trace was captured. */
  timestamp: string;
}

/** Vector embedding generated by an embedding provider. */
export type Embedding = number[];

/** Configuration for the chunking pipeline. */
export interface ChunkingConfig {
  /** Approximate target size of each chunk in characters. */
  size: number;
  /** Character overlap between consecutive chunks. */
  overlap: number;
}

/** Config that selects the retrieval strategies to run for a query. */
export interface QueryOptions {
  topK: number;
  strategies: RetrievalStrategy[];
  /** Rerank candidates = strategyK * this multiplier. */
  rerankCandidatesMultiplier?: number;
  /**
   * Restrict retrieval to rows whose metadata JSONB matches these
   * key/value pairs (equality). Example: { department: "legal" }.
   */
  filter?: Record<string, string | number | boolean>;
}

/** A full answer plus its trace, returned by rag.query(). */
export interface RagResult {
  answer: string;
  trace: RetrievalTrace;
}

export const DEFAULT_CHUNKING: ChunkingConfig = { size: 800, overlap: 100 };
export const DEFAULT_TOP_K = 5;